# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Csaba Kiraly
"""Session logs on disk: frontmatter, names, the index, the commits of session directories."""

import os
import subprocess
import sys
from pathlib import Path

from cudl.core import (
    CudlError, GIT, busy, changed_paths, commit_selected, git, git_retry, lab_lock, one_line,
    pinned_head, run, split_path, status_entries,
)
from cudl.lab import Lab, keep_since


INDEX_HEADER = (
    "# Session index\n\n"
    "Generated by `cudl index` from `journal/sessions/*.md`; do not edit.\n\n"
)


# What sessions write as they go, without anyone deciding to commit it: auto memory (main's memory/,
# shared by every worktree), plan mode (the session's plans/), and the session logs with their index.
SESSION_DIRS = ("memory", "plans", "journal")


INDEX = "journal/INDEX.md"


def select_paths(top, paths, untracked=True):
    """(paths to commit, split paths left alone, their states) among these files or directories. The
    session index isn't among them: it's generated, and commit_with_index writes and takes its own."""
    states = changed_paths(top, *paths)
    states.pop(INDEX, None)
    split = sorted(p for p, s in states.items() if split_path(s))
    take = sorted(p for p, s in states.items() if p not in split and (untracked or s[0][0] != "?"))
    return take, split, states


def committed_logs(top, take):
    """The session logs the commit about to be made will hold: HEAD's, less the ones it deletes, plus
    the ones it adds or changes."""
    logs = set(git(top, "ls-tree", "--name-only", "HEAD", "journal/sessions/", check=False).splitlines())
    for p in take:
        if p.startswith("journal/sessions/") and p.endswith(".md"):
            (logs.add if (Path(top) / p).exists() else logs.discard)(p)
    return logs


def commit_with_index(top, take, states, msg, extra=()):
    """commit_selected, with the session index rebuilt to list exactly the logs the commit will hold,
    never one it leaves out. The index is cudl's own generated file: cudl's version is the one
    committed, whatever was staged of it."""
    build_commit_index(top, take)
    state = changed_paths(top, INDEX).get(INDEX)
    if state and any(x not in " ?" for x, _ in state):
        run(GIT + ["reset", "-q", "--", INDEX], top, check=False)  # a staged copy gives way to cudl's
        state = changed_paths(top, INDEX).get(INDEX)
    if state:
        take, states = take + [INDEX], {**states, INDEX: state}
    return commit_selected(top, take, states, msg, extra)


def commit_session_dirs(lab, top, dirs, msg, untracked=True):
    """Commit what changed under these directories of a worktree, and nothing else, unless an operation
    is in progress there; with journal/ among them, the index lists exactly the logs committed."""
    with lab_lock(lab):
        if busy(top):
            return False
        take, split, states = select_paths(top, dirs, untracked)
        old = pinned_head(top)
        if (commit_with_index if "journal" in dirs else commit_selected)(top, take, states, msg):
            keep_since(Lab(top), old)
            return True
        return False



def ended_logs(fw):
    """This worktree's uncommitted logs of sessions that have ended: the commit their ends couldn't make
    (it failed, on signing say). Only what a commit can take as it is: sync and finish commit these."""
    logs = []
    for path in changed_paths(fw.top, "journal/sessions"):
        fm = readable_frontmatter(fw.top / path) if path.endswith(".md") and (fw.top / path).is_file() else {}
        if fm.get("ended") and not fm.get("running_since"):
            logs.append(path)
    return select_paths(fw.top, logs)[0] if logs else []


def ended_leftovers(fw):
    """What the checks before sync and finish leave out, because commit_ended_logs commits it: the ended
    sessions' logs, and the session index when there are any (an end's commit writes it first)."""
    logs = ended_logs(fw)
    return logs + [INDEX] if logs else []


def commit_ended_logs(fw, before):
    """Commit ended_logs, as the sessions' ends would have. The checks before it left them out, so if the
    commit fails, nothing may go on: the logs would go with the worktree."""
    with lab_lock(fw):
        take = ended_logs(fw)
        if not take:
            return
        states = select_paths(fw.top, take)[2]
        try:
            done = commit_with_index(fw.top, take, states, f"journal: logs of ended sessions that their ends "
                                                           f"couldn't commit, before {before}")
        except CudlError as e:  # with the signing diagnosis, when signing was the cause
            raise CudlError(f"the logs of ended sessions couldn't be committed ({', '.join(take)}):\n{e}") from None
        if not done:  # nothing a commit would record after all
            return
    print(f"committed {', '.join(Path(p).name for p in take)}: " + ("its session ended without committing it"
          if len(take) == 1 else "their sessions ended without committing them"))

FM_KEYS = ["session", "date", "feature", "agent", "role", "parent", "outer", "from", "features", "last_feature", "started", "running_since", "ended", "goal", "outcome", "next", "tags",
           "compactions", "needs_summary", "source", "branch", "transcript", "lab", "repos", "touched"]


def read_frontmatter(p):
    return parse_frontmatter(Path(p).read_text())


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end < 0:
        return {}, text
    fm = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    body = text[end + 4:].lstrip("\n")
    return fm, body


def write_frontmatter(p, fm, body):
    """Write a log whole (a session reading it never sees half of it), through a temporary file in the
    worktree's git dir, out of `git add`'s reach. A log that was staged and unchanged since stays
    staged, with this content: cudl's own writes never leave it staged-and-changed (see split_path)."""
    p = Path(p)
    keys = [k for k in FM_KEYS if k in fm] + [k for k in fm if k not in FM_KEYS]
    text = "\n".join(["---"] + [f"{k}: {fm[k]}".rstrip() for k in keys] + ["---", ""]) + body
    state = [(x, y) for x, y, _ in status_entries(p.parent, p.name)] if p.exists() else []
    gitdir = run(GIT + ["rev-parse", "--absolute-git-dir"], p.parent, check=False).stdout.strip()
    tmp = Path(gitdir or p.parent) / f"cudl-{p.name}.{os.getpid()}.tmp"
    try:
        tmp.write_text(text)
        os.replace(tmp, p)
    except OSError:
        p.write_text(text)  # another filesystem (EXDEV): written in place
    finally:
        tmp.unlink(missing_ok=True)
    if len(state) == 1 and state[0][0] not in " ?" and state[0][1] == " ":
        try:  # another git command may hold the index for a moment
            git_retry(p.parent, "--literal-pathspecs", "add", "--", p.name, tries=5)
        except CudlError as e:
            print(f"cudl: {p.name} was staged; restaging it after cudl's update failed: {e}", file=sys.stderr)


def readable_frontmatter(p):
    """The frontmatter of a log another session may be dropping or writing: {} if it's gone or unreadable."""
    try:
        return read_frontmatter(p)[0]
    except (OSError, UnicodeDecodeError):
        return {}


def update_frontmatter(p, **updates):
    fm, body = read_frontmatter(p)
    fm.update({k: v for k, v in updates.items() if v is not None})
    write_frontmatter(p, fm, body)


def sessions_dir(top):
    return Path(top) / "journal" / "sessions"


def session_file(top, sid, feature=None):
    """The log of session sid, in this worktree's journal. File names carry an id prefix, so check
    the full id inside; with `feature`, only a log written for that feature (a stacked feature's
    branch also carries its parent's logs)."""
    for p in sorted(sessions_dir(top).glob(f"*-{sid[:8]}*.md")):
        fm = readable_frontmatter(p)
        if fm.get("session") == sid and (feature is None or fm.get("feature") == feature):
            return p
    return None


def drop_frontmatter(p, *keys):
    fm, body = read_frontmatter(p)
    if any(k in fm for k in keys):
        write_frontmatter(p, {k: v for k, v in fm.items() if k not in keys}, body)


def session_path(top, stem, sid):
    """A new log's path: <stem>-<id prefix>.md, the prefix long enough to be unused.

    Codex ids are time-ordered, so sessions started close together share their first characters.
    """
    compact = sid.replace("-", "")
    for n in (8, 12, 16, len(compact)):
        p = sessions_dir(top) / f"{stem}-{compact[:n]}.md"
        if not p.exists():
            return p
    raise CudlError(f"a session log for {sid} already exists")


def create_log(w, stem, sid, fm, body):
    """A new log, its name (an id prefix not yet taken) chosen and written under the lab lock: Codex ids
    are time-ordered, so two sessions starting together share their first characters."""
    with lab_lock(w):
        sessions_dir(w.top).mkdir(parents=True, exist_ok=True)
        p = session_path(w.top, stem, sid)
        write_frontmatter(p, fm, body)
    return p


def build_index(top, tracked_only=False):
    """journal/INDEX.md from the session logs: all of them, or those in the git index (tracked_only).
    A log that can't be read is left out, not a reason to fail."""
    rows = []
    tracked = set(git(top, "ls-files", "journal/sessions").splitlines()) if tracked_only else None
    for p in sessions_dir(top).glob("*.md"):
        if tracked is not None and str(p.relative_to(top)) not in tracked:
            continue
        fm = readable_frontmatter(p)
        if fm:
            rows.append((fm.get("started", p.name), p.name, fm))
    return write_index(top, rows)


def build_commit_index(top, take):
    """journal/INDEX.md as the commit about to be made will hold it: its logs (committed_logs), each
    as that commit has it: the working tree's version of a log it takes, HEAD's of the others (which
    may have changed, or gone, here without being part of it)."""
    changed = changed_paths(top, "journal/sessions")
    rows = []
    for rel in sorted(committed_logs(top, take)):
        name = Path(rel).name
        if rel in take or rel not in changed:
            fm = readable_frontmatter(Path(top) / rel)
        else:
            blob = subprocess.run(GIT + ["show", f"HEAD:{rel}"], cwd=top, capture_output=True).stdout
            fm = parse_frontmatter(blob.decode("utf-8", "replace"))[0]
        if fm:
            rows.append((fm.get("started", name), name, fm))
    return write_index(top, rows)


def write_index(top, rows):
    rows.sort()
    present = {fm.get("session") for _, _, fm in rows}
    children = {}
    for row in rows:
        if row[2].get("parent") in present:
            children.setdefault(row[2]["parent"], []).append(row)
    lines = []

    def link(name):
        return f"[{name[:-len('.md')].rsplit('-', 1)[-1]}](sessions/{name})"  # the file's id prefix

    shown = set()

    def entry(name, fm):
        shown.add(name)
        line = (f"- {fm.get('date', '?')} · {fm.get('feature', '?')} · {link(name)} · "
                f"{fm.get('agent') or 'claude'} · {fm.get('outcome') or 'open'} · {fm.get('goal') or '(no goal)'}")
        lines.append(line + (f" → next: {fm['next']}" if fm.get("next") else ""))
        descendants(fm.get("session"), 1)

    def descendants(session, depth):
        for _, cname, cfm in children.get(session, []):
            if cname not in shown:  # a cycle of parents ends here
                shown.add(cname)
                lines.append(f"{'  ' * depth}- ↳ {cfm.get('agent') or 'claude'} {link(cname)} · "
                             f"{one_line(cfm.get('goal') or '(no prompt)', 110)}")
                descendants(cfm.get("session"), depth + 1)

    for _, name, fm in rows:
        if fm.get("parent") not in present:  # a child is listed under its parent
            entry(name, fm)
    for _, name, fm in rows:
        if name not in shown:  # sessions whose parents form a cycle: no one is on top, list them anyway
            entry(name, fm)
    f = Path(top) / "journal" / "INDEX.md"
    text = INDEX_HEADER + "\n".join(lines) + ("\n" if lines else "")
    f.parent.mkdir(parents=True, exist_ok=True)
    if not f.exists() or f.read_text() != text:
        f.write_text(text)
    return lines


def last_session(top, label):
    files = sorted(sessions_dir(top).glob(f"*-{label}-*.md"))
    if not files:
        return None
    fm, _ = read_frontmatter(files[-1])
    s = f"{fm.get('date', '?')} {fm.get('session', '')[:8]} {fm.get('outcome') or 'open'}"
    if fm.get("next"):
        s += f" → {fm['next']}"
    return s


def commit_memory(w, msg=None):
    """From a feature, commit the shared memory directory on main (not while main is busy)."""
    if not (w.main / "memory").is_dir():
        return False
    return bool(commit_session_dirs(w, w.main, ["memory"], msg or f"memory: from {w.label}"))
